import argparse
from label_studio_sdk import Client


def setup(port: int, token: str):
    # Define the URL where Label Studio is accessible and the API key for your user account
    LABEL_STUDIO_URL = f"http://localhost:{port}"
    # Connect to the Label Studio API and check the connection
    ls = Client(url=LABEL_STUDIO_URL, api_key=token)
    ls.check_connection()

    project = ls.start_project(
        title="Logo Bounding Box Annotation",
        label_config="""
        <View>
        <Image name="image" value="$image" zoom="true"/>
        <RectangleLabels name="label" toName="image">
        <Label value="100 Wealth" />
        <Label value="100PLUS" />
        <Label value="2P" />
        <Label value="3BB" />
        <Label value="3M" />
        <Label value="4U2" />
        <Label value="7-Eleven" />
        <Label value="AIA" />
        <Label value="AIS" />
        <Label value="AKA Japanese Restaurant" />
        <Label value="ANANDA" />
        <Label value="ANANTA" />
        <Label value="AOC" />
        <Label value="AP" />
        <Label value="ASUS" />
        <Label value="AXE" />
        <Label value="Acer" />
        <Label value="Acne-Aid" />
        <Label value="Aconatic" />
        <Label value="Ad Addict" />
        <Label value="Adidas" />
        <Label value="After You" />
        <Label value="Agoda" />
        <Label value="Ai Japanese Village" />
        <Label value="Allianz Ayudhya" />
        <Label value="Amari" />
        <Label value="Amarin TV" />
        <Label value="American Standard" />
        <Label value="Ananta River Hills" />
        <Label value="Anantara" />
        <Label value="Anlene" />
        <Label value="Anmum" />
        <Label value="AnyMind" />
        <Label value="Apple" />
        <Label value="Aquafina" />
        <Label value="Areeya" />
        <Label value="Artistry" />
        <Label value="Asia Hospital" />
        <Label value="Aston Martin" />
        <Label value="Audi" />
        <Label value="Audrey Cafe &amp; Bistro" />
        <Label value="Aurora" />
        <Label value="Avani+" />
        <Label value="BAAC" />
        <Label value="BBC Thai" />
        <Label value="BIODERMA" />
        <Label value="BMW" />
        <Label value="BNH Hospital" />
        <Label value="BRAND’S" />
        <Label value="BTS SkyTrain" />
        <Label value="BUZZPURR" />
        <Label value="BaNANA" />
        <Label value="Babalah" />
        <Label value="Babi Mild" />
        <Label value="Baby Bright" />
        <Label value="Baby Moby" />
        <Label value="BabyLove" />
        <Label value="Bangchak" />
        <Label value="Bangkok Airways" />
        <Label value="Bangkok Bank" />
        <Label value="Bangkok Biz News" />
        <Label value="Bangkok Christian Hospital" />
        <Label value="Bangkok Hospital" />
        <Label value="Bangkok Hospital Siriroj" />
        <Label value="Bangkok Insurance" />
        <Label value="Bangkoklife" />
        <Label value="Bangmod Hospital" />
        <Label value="Bangpakok Hospital" />
        <Label value="Bangpo General Hospital" />
        <Label value="Banyan Tree" />
        <Label value="Bar B Q Plaza" />
        <Label value="Baskin-Robbins" />
        <Label value="BeNice" />
        <Label value="Bear Brand" />
        <Label value="Beauty Buffet Shop" />
        <Label value="Beger Paint" />
        <Label value="Beko" />
        <Label value="BenQ" />
        <Label value="Benefit Cosmetics" />
        <Label value="Bhumirajnakarin Kidney Institute Hospital" />
        <Label value="Big C" />
        <Label value="Biotherm Homme" />
        <Label value="Birdy" />
        <Label value="Bisous Bisous" />
        <Label value="Bitkub" />
        <Label value="Bluebik" />
        <Label value="Blúport Huahin" />
        <Label value="BnB home" />
        <Label value="Bobbi Brown" />
        <Label value="Boonthavorn" />
        <Label value="Brand Buffet" />
        <Label value="BrandAge" />
        <Label value="Bridgestone" />
        <Label value="Browit By Nongchat" />
        <Label value="Bua Concrete" />
        <Label value="Bumrungrad International Hospital" />
        <Label value="Burger King" />
        <Label value="C-vitt" />
        <Label value="CALTEX" />
        <Label value="CH8" />
        <Label value="CIMB" />
        <Label value="CJ MORE" />
        <Label value="CNMI Ramathibodi Hospital" />
        <Label value="CONWOOD" />
        <Label value="COOLfahrenheit" />
        <Label value="COSLUXE" />
        <Label value="COTTO" />
        <Label value="CP" />
        <Label value="CPAC" />
        <Label value="CREATIVE TALK" />
        <Label value="Café Amazon" />
        <Label value="Camillian Hospital" />
        <Label value="Canon" />
        <Label value="Captain Coating" />
        <Label value="Carabao" />
        <Label value="Care" />
        <Label value="Carrier" />
        <Label value="Casio" />
        <Label value="Cat Radio" />
        <Label value="Cathy Doll" />
        <Label value="Centara" />
        <Label value="Central Department Store" />
        <Label value="CentralWorld" />
        <Label value="Cetaphil" />
        <Label value="Ch7HD" />
        <Label value="Chang" />
        <Label value="Channel 3 HD" />
        <Label value="Chao Phraya Express Boat" />
        <Label value="Chaophya Hospital" />
        <Label value="Chester's" />
        <Label value="Chevrolet" />
        <Label value="Chewathai" />
        <Label value="Cho Cosmetics" />
        <Label value="Chulabhorn Hospital" />
        <Label value="Chularat Hospital Group" />
        <Label value="Citi" />
        <Label value="Clean &amp; Clear" />
        <Label value="Clear" />
        <Label value="Clear Nose" />
        <Label value="Clinique" />
        <Label value="Coca-Cola" />
        <Label value="Cocoburi" />
        <Label value="Colgate" />
        <Label value="Cornetto" />
        <Label value="Corsair" />
        <Label value="Crystal Drinking Water" />
        <Label value="Cubic Bread" />
        <Label value="Cute Press" />
        <Label value="D-nee" />
        <Label value="DENTISTE'" />
        <Label value="DON DON DONKI" />
        <Label value="DUTCHIE YOGHURT" />
        <Label value="Daikin" />
        <Label value="Daily News" />
        <Label value="Dairy Queen" />
        <Label value="Daradaily" />
        <Label value="Dell" />
        <Label value="Dentyne" />
        <Label value="Dhipaya Insurance" />
        <Label value="Diamond Brand" />
        <Label value="Dibuk Hospital" />
        <Label value="Digital Tips" />
        <Label value="Dna soy milk" />
        <Label value="Dohome" />
        <Label value="Doi Kham" />
        <Label value="Dolfin" />
        <Label value="Domino's Pizza" />
        <Label value="Double A" />
        <Label value="Dove" />
        <Label value="Dr.Jill" />
        <Label value="Ducati" />
        <Label value="Dulux" />
        <Label value="Dumex" />
        <Label value="Dunkin'" />
        <Label value="Dusit Thani" />
        <Label value="Dutch Mill" />
        <Label value="Dyson" />
        <Label value="ECOVACS" />
        <Label value="ESTRO" />
        <Label value="ETUDE" />
        <Label value="Eglips" />
        <Label value="Electrolux" />
        <Label value="Elephant Gypsum Board" />
        <Label value="Emporium" />
        <Label value="Emquartier" />
        <Label value="Enfa" />
        <Label value="Entravision MediaDonuts" />
        <Label value="Epson" />
        <Label value="Esso" />
        <Label value="Estee Lauder" />
        <Label value="Eucerin" />
        <Label value="Eurofood" />
        <Label value="Expedia" />
        <Label value="FINN MOBILE" />
        <Label value="FINNOMENA" />
        <Label value="FUJIFILM" />
        <Label value="FWD" />
        <Label value="Facebook" />
        <Label value="FamilyMart" />
        <Label value="Fanta" />
        <Label value="Farm Design" />
        <Label value="Fashionisland" />
        <Label value="Ferrari" />
        <Label value="Ferrero Rocher" />
        <Label value="Five Star Chicken" />
        <Label value="Flash Express" />
        <Label value="Foodland" />
        <Label value="Ford" />
        <Label value="Foremost" />
        <Label value="Frasers Property Home" />
        <Label value="Fuji Restaurant" />
        <Label value="Future Trends" />
        <Label value="GD-Jewelry" />
        <Label value="GM Live" />
        <Label value="GMM25" />
        <Label value="GPX" />
        <Label value="GRAND UNITY" />
        <Label value="Garena" />
        <Label value="Garnier" />
        <Label value="Gateway Ekamai" />
        <Label value="Gaysorn Village" />
        <Label value="Generali" />
        <Label value="Giffarine" />
        <Label value="Glico" />
        <Label value="Global House" />
        <Label value="Gourmet Market" />
        <Label value="Government Housing Bank" />
        <Label value="Government Saving Bank" />
        <Label value="Grab" />
        <Label value="HERSHEY'S" />
        <Label value="HIS" />
        <Label value="HOT POT BUFFET" />
        <Label value="HP" />
        <Label value="Hada Labo" />
        <Label value="Haier" />
        <Label value="Harley-Davidson" />
        <Label value="Häagen-Dazs" />
        <Label value="Häfele" />
        <Label value="Head and Shoulders" />
        <Label value="Heineken" />
        <Label value="Heinz" />
        <Label value="Herbal Essences" />
        <Label value="Hi-Q" />
        <Label value="Hilton" />
        <Label value="Hino" />
        <Label value="Hitachi" />
        <Label value="Holika Holika" />
        <Label value="HomePro" />
        <Label value="Honda" />
        <Label value="Hua Seng Heng" />
        <Label value="Huachiew Hospital" />
        <Label value="Huawei" />
        <Label value="Huggies" />
        <Label value="Hyatt Regency" />
        <Label value="Hyundai" />
        <Label value="ICBC Thai Commercial Bank" />
        <Label value="ICHITAN" />
        <Label value="ICONSIAM" />
        <Label value="IKEA" />
        <Label value="IN2IT" />
        <Label value="INSEE" />
        <Label value="IRPC" />
        <Label value="ISUZU" />
        <Label value="Index Living Mall" />
        <Label value="Instagram" />
        <Label value="InterContinental" />
        <Label value="Inzpy" />
        <Label value="Islamic Bank" />
        <Label value="J&amp;T Express" />
        <Label value="JD" />
        <Label value="JIB" />
        <Label value="JOHNSON'S" />
        <Label value="JORAKAY" />
        <Label value="Jaymart" />
        <Label value="Jele Beautie" />
        <Label value="Jones Salad" />
        <Label value="Jotun" />
        <Label value="Joylada" />
        <Label value="Jubilee Diamond" />
        <Label value="K-Village" />
        <Label value="KFC" />
        <Label value="KOHLER" />
        <Label value="KTC" />
        <Label value="Kaidee" />
        <Label value="Kasemrad Hospital" />
        <Label value="Kasikorn Bank" />
        <Label value="Kawasaki" />
        <Label value="Keeway" />
        <Label value="Kerry Express" />
        <Label value="Khaosod" />
        <Label value="Kia" />
        <Label value="Kiatnakin Phatra Bank" />
        <Label value="Kiehl's" />
        <Label value="Kinder" />
        <Label value="King Chulalongkorn Memorial Hospital" />
        <Label value="King Power" />
        <Label value="Kingston" />
        <Label value="KitKat" />
        <Label value="Klook" />
        <Label value="Kluaynamthai Hospital" />
        <Label value="Knorr" />
        <Label value="Kodomo" />
        <Label value="KomChadLuek" />
        <Label value="Koncept Furniture" />
        <Label value="Kouen" />
        <Label value="KratingDaeng" />
        <Label value="Krispy Kreme" />
        <Label value="Krung Siam St.Calos Medical Centre" />
        <Label value="Krungsri Bank" />
        <Label value="Krungsri First Choice" />
        <Label value="Krungthai Bank" />
        <Label value="L'OCCITANE" />
        <Label value="L'Oréal Paris" />
        <Label value="LALIN Property" />
        <Label value="LAMPTAN" />
        <Label value="LANEIGE" />
        <Label value="LEO" />
        <Label value="LG" />
        <Label value="LINE BK" />
        <Label value="LINE MAN" />
        <Label value="LINE WEBTOON" />
        <Label value="LPN" />
        <Label value="LUX" />
        <Label value="La Mer" />
        <Label value="La Roche-Posay" />
        <Label value="Lactasoy" />
        <Label value="Ladies of Digital Age" />
        <Label value="Lalamove" />
        <Label value="Lamoon" />
        <Label value="Lancôme" />
        <Label value="Land Rover" />
        <Label value="Land and Houses" />
        <Label value="Land and Houses Bank" />
        <Label value="Laurier My Brand" />
        <Label value="Lawson108" />
        <Label value="Lays" />
        <Label value="Lazada" />
        <Label value="LazMall" />
        <Label value="Le Méridien" />
        <Label value="Le Pan Bakery" />
        <Label value="Leica" />
        <Label value="Lelux Plastic Surgery Hospital" />
        <Label value="Lenovo" />
        <Label value="Lesasha" />
        <Label value="Lexus" />
        <Label value="Lienjang" />
        <Label value="Lion Air" />
        <Label value="LnwShop" />
        <Label value="Logitech" />
        <Label value="Lotus's" />
        <Label value="M-150" />
        <Label value="MAGGI" />
        <Label value="MANSOME" />
        <Label value="MBK Center" />
        <Label value="MCOT" />
        <Label value="MEILINDA" />
        <Label value="MERREZ'CA" />
        <Label value="MG" />
        <Label value="MIKIMOTO" />
        <Label value="MILO" />
        <Label value="MINI" />
        <Label value="MK Restaurants" />
        <Label value="MOGEN" />
        <Label value="MRT" />
        <Label value="MSI" />
        <Label value="MSIG" />
        <Label value="MTI" />
        <Label value="Magnolia Quality Development Corporation" />
        <Label value="Magnum" />
        <Label value="Mahachai Hospital" />
        <Label value="Major Cineplex" />
        <Label value="Major Development" />
        <Label value="Makro" />
        <Label value="Malee" />
        <Label value="Mama" />
        <Label value="Mamonde" />
        <Label value="MamyPoko" />
        <Label value="Manager Online" />
        <Label value="Marketeer" />
        <Label value="Marketing Oops" />
        <Label value="Marriott" />
        <Label value="Maserati" />
        <Label value="MaxValu" />
        <Label value="Maybelline New York" />
        <Label value="Mazda" />
        <Label value="McDonald's" />
        <Label value="McLaren" />
        <Label value="Mee Cosmetics" />
        <Label value="Megabangna" />
        <Label value="Meiji" />
        <Label value="Mellow for Kids" />
        <Label value="Mentos" />
        <Label value="Mercedes-Benz" />
        <Label value="Mercure" />
        <Label value="Merries" />
        <Label value="Meta" />
        <Label value="Michelin" />
        <Label value="Mille" />
        <Label value="Minéré" />
        <Label value="Miniso" />
        <Label value="Ministry of Public Health" />
        <Label value="Minute Maid" />
        <Label value="Mission Hospital" />
        <Label value="Mister Donut" />
        <Label value="Mister Robot" />
        <Label value="Mistine" />
        <Label value="Mitr Phol Sugar" />
        <Label value="Mitsubishi" />
        <Label value="Miyabi Grill" />
        <Label value="MizuMi" />
        <Label value="Moccona" />
        <Label value="Mommy Bear" />
        <Label value="Mono 29" />
        <Label value="Motorola" />
        <Label value="Mövenpick" />
        <Label value="Muang Thai Life" />
        <Label value="Munkong Property" />
        <Label value="M•A•C Cosmetics" />
        <Label value="NESCAFÉ" />
        <Label value="NESVITA" />
        <Label value="NIVEA" />
        <Label value="NT Broadband" />
        <Label value="NT Cloud" />
        <Label value="NYX" />
        <Label value="Nakhonchaiair" />
        <Label value="Nakornthon Hospital" />
        <Label value="Nami" />
        <Label value="Namthip" />
        <Label value="Narai Property" />
        <Label value="NationTV" />
        <Label value="National Broadcasting Services of Thailand" />
        <Label value="National Telecom" />
        <Label value="Naturegift" />
        <Label value="Nestlé Pure Life" />
        <Label value="Neutrogena" />
        <Label value="Newtv" />
        <Label value="Ngerntidlor" />
        <Label value="Nikon" />
        <Label value="Nippon Paint" />
        <Label value="Nissan" />
        <Label value="Nitipon Clinic" />
        <Label value="Noble Development" />
        <Label value="Nok Air" />
        <Label value="Nonthavej Hospital" />
        <Label value="Novotel" />
        <Label value="OPPO" />
        <Label value="OREO" />
        <Label value="Oab's Soap" />
        <Label value="Oakwood" />
        <Label value="Ocean Life Insurance" />
        <Label value="Oishi Drink" />
        <Label value="Oishi Food" />
        <Label value="Olay" />
        <Label value="Onegems" />
        <Label value="Ootoya Japanese Restaurant" />
        <Label value="Oriental Princess" />
        <Label value="Origin Property" />
        <Label value="Origins" />
        <Label value="Ovaltine" />
        <Label value="PABLO" />
        <Label value="PAÑPURI" />
        <Label value="PMG Hospital" />
        <Label value="POND'S" />
        <Label value="PPTV" />
        <Label value="PTG Energy" />
        <Label value="PTT" />
        <Label value="PTT NGV" />
        <Label value="Panasonic" />
        <Label value="Pandora" />
        <Label value="Pantene" />
        <Label value="Pantip" />
        <Label value="Paolo Hospital" />
        <Label value="Paula's Choice" />
        <Label value="Peachy" />
        <Label value="Penguin Eat Shabu" />
        <Label value="Pepsi" />
        <Label value="Peptein" />
        <Label value="Petch Mangkorn Jewelry" />
        <Label value="Petchchompoo Jewelry" />
        <Label value="Peugeot" />
        <Label value="Philips" />
        <Label value="Phyathai Hospital" />
        <Label value="Physicians Formula" />
        <Label value="Pigeon" />
        <Label value="Pioneer" />
        <Label value="Piyavate Hospital" />
        <Label value="Pizza Hut" />
        <Label value="Pocky" />
        <Label value="Police General Hospital" />
        <Label value="Pornkasem Clinic" />
        <Label value="Porsche" />
        <Label value="Positioning Magazine" />
        <Label value="PostToday" />
        <Label value="Power Buy" />
        <Label value="Prachatai" />
        <Label value="Praram 9 hospital" />
        <Label value="Prima" />
        <Label value="Pringles" />
        <Label value="Prinsiri" />
        <Label value="Property Perfect" />
        <Label value="Protex" />
        <Label value="Proud Gems" />
        <Label value="Prudential" />
        <Label value="Pruksa" />
        <Label value="Pullman" />
        <Label value="Pumpnom" />
        <Label value="Puriku" />
        <Label value="Q.House" />
        <Label value="RAD Cosmetics" />
        <Label value="RAN_cosmetic" />
        <Label value="RAiNMaker" />
        <Label value="Rabbit LINE Pay" />
        <Label value="Rajavithi Hospital" />
        <Label value="Ramkhamhaeng Hospital" />
        <Label value="Rascal + Friends" />
        <Label value="Ready Energy Drink" />
        <Label value="Rejoice" />
        <Label value="Renaissance" />
        <Label value="Revlon" />
        <Label value="Richell Baby" />
        <Label value="Robinson" />
        <Label value="Rojukiss" />
        <Label value="Rolls-Royce" />
        <Label value="Rosdee" />
        <Label value="Ruam Chai Pracharug Hospital" />
        <Label value="S&amp;P" />
        <Label value="S-26" />
        <Label value="SANWA" />
        <Label value="SB Design Square" />
        <Label value="SC ASSET" />
        <Label value="SENA Development" />
        <Label value="SF Cinema" />
        <Label value="SHERA" />
        <Label value="SHOW DC" />
        <Label value="SIAMWELL JEWELRY" />
        <Label value="SINGHA COMPLEX" />
        <Label value="SK-II" />
        <Label value="SNAILWHITE" />
        <Label value="SPY Wine Cooler" />
        <Label value="STIEBEL ELTRON" />
        <Label value="SUSCO" />
        <Label value="Saint Louis Hospital" />
        <Label value="Salika" />
        <Label value="Samitivej Hospital" />
        <Label value="Samsung" />
        <Label value="Samyan Mitrtown" />
        <Label value="SangSom" />
        <Label value="Sansiri" />
        <Label value="Santa Fe' Steak" />
        <Label value="Schneider Electric" />
        <Label value="Scotch" />
        <Label value="Seacon Square" />
        <Label value="Senka" />
        <Label value="Sensodyne" />
        <Label value="Shangri-La Hotel" />
        <Label value="Shell" />
        <Label value="Sheraton" />
        <Label value="Shizuoka" />
        <Label value="Shopee" />
        <Label value="ShopeePay" />
        <Label value="Siam Cement Group" />
        <Label value="Siam Center" />
        <Label value="Siam Commercial Bank" />
        <Label value="Siam Discovery" />
        <Label value="Siam Kubota" />
        <Label value="Siam Paragon" />
        <Label value="Siam Square One" />
        <Label value="Siam Takashimaya" />
        <Label value="Sikarin Hospital" />
        <Label value="Singha Beer" />
        <Label value="Singha Drinking Water" />
        <Label value="Singha Estate" />
        <Label value="Siriraj Piyamaharajkarun Hospital" />
        <Label value="Sizzler" />
        <Label value="Smooth-E" />
        <Label value="Smooto Japan" />
        <Label value="Soda Singha" />
        <Label value="Sofitel Hotel" />
        <Label value="Sombat Tour" />
        <Label value="Sony" />
        <Label value="Sponsor" />
        <Label value="Spring News" />
        <Label value="Sprinkle" />
        <Label value="Sri panwa" />
        <Label value="Srichand" />
        <Label value="Srisawad" />
        <Label value="Starbucks" />
        <Label value="Studio 7" />
        <Label value="Sukumvit Hospital" />
        <Label value="Sulwhasoo" />
        <Label value="SunSnackDunk" />
        <Label value="Sunbites" />
        <Label value="Sunrise Tacos" />
        <Label value="Sunsilk" />
        <Label value="Supalai" />
        <Label value="Supermom" />
        <Label value="Sushi Hiro" />
        <Label value="Suzuki" />
        <Label value="Swensen's" />
        <Label value="Swissôtel Hotel" />
        <Label value="Syn Mun Kong Insurance" />
        <Label value="Synphaet Children Hospital" />
        <Label value="Synphaet Hospital" />
        <Label value="TCL" />
        <Label value="TER Cosmetics" />
        <Label value="THAI Smile Airways" />
        <Label value="THE STANDARD" />
        <Label value="THEFACESHOP" />
        <Label value="THREE" />
        <Label value="TISCO" />
        <Label value="TMBThanachart Bank" />
        <Label value="TNN" />
        <Label value="TOA" />
        <Label value="TOTO" />
        <Label value="TPI Polene" />
        <Label value="TRESemmé" />
        <Label value="TV Direct" />
        <Label value="TV5" />
        <Label value="Taokaenoi" />
        <Label value="TechMatrix" />
        <Label value="Techsauce" />
        <Label value="Tefal" />
        <Label value="Tenjo" />
        <Label value="Terminal21" />
        <Label value="Texas Chicken" />
        <Label value="Thai Airways" />
        <Label value="Thai Credit Retail Bank" />
        <Label value="Thai Life Insurance" />
        <Label value="Thai PBS" />
        <Label value="Thai Post" />
        <Label value="Thai Watsadu" />
        <Label value="Thai-Denmark" />
        <Label value="Thailand Post" />
        <Label value="Thainakarin Hospital" />
        <Label value="ThairathTV" />
        <Label value="Thairung" />
        <Label value="Thammasat University Hospital" />
        <Label value="Thanachart Insurance" />
        <Label value="The History Of Whoo" />
        <Label value="The MATTER" />
        <Label value="The Mall" />
        <Label value="The Nation" />
        <Label value="The Opener" />
        <Label value="The People" />
        <Label value="The Pizza Company" />
        <Label value="The Story" />
        <Label value="The Street" />
        <Label value="The Transport" />
        <Label value="Thonburi Hospital" />
        <Label value="Thongbai Burapha Jewelry" />
        <Label value="Thumbsup" />
        <Label value="Tiger Brand" />
        <Label value="TikTok" />
        <Label value="Tipco" />
        <Label value="Tops" />
        <Label value="Toshiba" />
        <Label value="Toyota" />
        <Label value="Traveloka" />
        <Label value="Triumph" />
        <Label value="True Music" />
        <Label value="True Sports" />
        <Label value="True4U" />
        <Label value="TrueID" />
        <Label value="TrueMoney" />
        <Label value="TrueMove H" />
        <Label value="TrueOnline" />
        <Label value="TrueShopping" />
        <Label value="TrueVisions" />
        <Label value="Twelve Plus" />
        <Label value="Twitter" />
        <Label value="USTAR Cosmetics" />
        <Label value="UZIcosmetic" />
        <Label value="Umay+" />
        <Label value="Unif" />
        <Label value="United Overseas Bank" />
        <Label value="Unlockmen" />
        <Label value="Vajira Hospital" />
        <Label value="Vaseline" />
        <Label value="Vejthani Hospital" />
        <Label value="Verasu" />
        <Label value="Vespa" />
        <Label value="Vibharam Hospital" />
        <Label value="Vibhavadi Hospital" />
        <Label value="Vichaiyut Hospital" />
        <Label value="Vichy" />
        <Label value="Vietjet" />
        <Label value="ViewSonic" />
        <Label value="Vijittra's Jewellery" />
        <Label value="Villa Market" />
        <Label value="Viriyah Insurance" />
        <Label value="Vitamilk" />
        <Label value="Voice TV" />
        <Label value="Volvo" />
        <Label value="WISESIGHT" />
        <Label value="Wall's" />
        <Label value="Weber" />
        <Label value="Western Digital" />
        <Label value="Wet n Wild" />
        <Label value="Workpoint" />
        <Label value="Wuttisak" />
        <Label value="Xiaomi" />
        <Label value="Yamaha" />
        <Label value="Yanhee Hospital" />
        <Label value="Yaowarat Krungthep Jewelry" />
        <Label value="Yayoi Japanese Restaurant" />
        <Label value="YenYen" />
        <Label value="YouTube" />
        <Label value="Yves Rocher" />
        <Label value="ZEN Japanese Restaurant" />
        <Label value="Zeer Rangsit" />
        <Label value="a day" />
        <Label value="airasia" />
        <Label value="beartai" />
        <Label value="dtac" />
        <Label value="est" />
        <Label value="foodpanda" />
        <Label value="iStudio" />
        <Label value="ibis" />
        <Label value="innisfree" />
        <Label value="mMilk" />
        <Label value="modernform furniture" />
        <Label value="my by NT" />
        <Label value="one31" />
        <Label value="settrade" />
        <Label value="vivo" />
        <Label value="สมหวัง เงินสั่งได้" />
        <Label value="อาคเนย์" />
        <Label value="เรื่องเล่าเช้านี้" />
        <Label value="Viu" />
        <Label value="Netflix" />
        <Label value="Disney+" />
        <Label value="WeTV" />
        <Label value="Prime Video" />
        <Label value="iQIYI" />
        <Label value="AIS PLAY" />
        <Label value="HBO" />
        <Label value="SUQQU" />
        <Label value="Asahi" />
        <Label value="CeraVe" />
        <Label value="CHANEL" />
        <Label value="GUCCI" />
        <Label value="KANEBO" />
        <Label value="KATE TOKYO" />
        <Label value="Nike" />
        <Label value="PUMA" />
        <Label value="Reebok" />
        <Label value="Yves Saint Laurent" />
        <Label value="พรรคก้าวไกล" />
        <Label value="พรรคชาติไทยพัฒนา" />
        <Label value="พรรคไทยภักดี" />
        <Label value="พรรคไทยสร้างไทย" />
        <Label value="พรรคประชาธิปัตย์" />
        <Label value="พรรคเพื่อไทย" />
        <Label value="พรรคพลังประชารัฐ" />
        <Label value="พรรคภูมิใจไทย" />
        <Label value="พรรครวมไทยสร้างชาติ" />
        <Label value="พรรคเสรีรวมไทย" />
        <Label value="สำนักงานปลัดกระทรวงกลาโหม" />
        <Label value="LOOX TV" />
        <Label value="AURA Mineral Water" />
        <Label value="Purra" />
        <Label value="SIAM PIWAT" />
        <Label value="SIAM PREMIUM OUTLETS BANGKOK" />
        <Label value="พรรคชาติพัฒนากล้า" />
        <Label value="Corona" />
        <Label value="MY BEER" />
        <Label value="Snowy Weizen" />
        <Label value="Carlsberg" />
        <Label value="Kronenbourg" />
        <Label value="Hoegaarden" />
        <Label value="Budweiser" />
        <Label value="Mont Fleur" />
        <Label value="Haru Cold Brew Green Tea" />
        <Label value="Kadprai" />
        <Label value="Boss Coffee" />
        <Label value="Bomi" />
        <Label value="Metropolitan Electricity Authority" />
        <Label value="Arabus Coffee" />
        <Label value="สำนักงานตำรวจแห่งชาติ" />
        <Label value="สำนักงานเทคโนโลยีสารสนเทศและการสื่อสาร - สำนักงานตำรวจแห่งชาติ" />
        <Label value="Export-Import Bank" />
        <Label value="BRITANIA" />
        <Label value="BANK OF THAILAND" />
        <Label value="Token X" />
        <Label value="SCBX" />
        <Label value="SCB Abacus" />
        <Label value="SCB 10X" />
        <Label value="MONIX" />
        <Label value="InnovestX" />
        <Label value="CardX" />
        <Label value="AutoX" />
        <Label value="Alpha X" />
        <Label value="era-won" />
        <Label value="absorba" />
        <Label value="Chulalongkorn University" />
        <Label value="Bangkok University" />
        <Label value="besico" />
        <Label value="Robinhood" />
        <Label value="Thammasat University" />
        <Label value="era-won beauty" />
        <Label value="Krungthai AXA" />
        <Label value="CPRAM" />
        <Label value="Charoen Pokphand Group C.P. Group" />
        <Label value="CPALL" />
        <Label value="Schweppes" />
        <Label value="SINGHA LEMON SODA" />
        <Label value="DHL" />
        <Label value="Ninja Van" />
        <Label value="SPX Express" />
        <Label value="Tesla" />
        <Label value="การท่องเที่ยวแห่งประเทศไทย" />
        <Label value="Bangkok Hospital Siriroj" />
        <Label value="Bangkok Insurance" />
        <Label value="Bangkoklife" />
        <Label value="Bangmod Hospital" />
        <Label value="Bangpakok Hospital" />
        <Label value="Bangpo General Hospital" />
        <Label value="Banyan Tree" />
        <Label value="Bar B Q Plaza" />
        <Label value="Baskin-Robbins" />
        <Label value="BeNice" />
        <Label value="Bear Brand" />
        <Label value="Beauty Buffet Shop" />
        <Label value="Beger Paint" />
        <Label value="Beko" />
        <Label value="BenQ" />
        <Label value="Benefit Cosmetics" />
        <Label value="Bhumirajnakarin Kidney Institute Hospital" />
        <Label value="Big C" />
        <Label value="Biotherm Homme" />
        <Label value="Birdy" />
        <Label value="Bisous Bisous" />
        <Label value="Bitkub" />
        <Label value="Bluebik" />
        <Label value="Blúport Huahin" />
        <Label value="BnB home" />
        <Label value="Bobbi Brown" />
        <Label value="Boonthavorn" />
        <Label value="Brand Buffet" />
        <Label value="BrandAge" />
        <Label value="Bridgestone" />
        <Label value="Browit By Nongchat" />
        <Label value="Bua Concrete" />
        <Label value="Bumrungrad International Hospital" />
        <Label value="Burger King" />
        <Label value="C-vitt" />
        <Label value="CALTEX" />
        <Label value="CH8" />
        <Label value="CIMB" />
        <Label value="CJ MORE" />
        <Label value="CNMI Ramathibodi Hospital" />
        <Label value="CONWOOD" />
        <Label value="COOLfahrenheit" />
        <Label value="COSLUXE" />
        <Label value="COTTO" />
        <Label value="CP" />
        <Label value="CPAC" />
        <Label value="CREATIVE TALK" />
        <Label value="Café Amazon" />
        <Label value="Camillian Hospital" />
        <Label value="Canon" />
        <Label value="Captain Coating" />
        <Label value="Carabao" />
        <Label value="Care" />
        <Label value="Carrier" />
        <Label value="Casio" />
        <Label value="Cat Radio" />
        <Label value="Cathy Doll" />
        <Label value="Centara" />
        <Label value="Central Department Store" />
        <Label value="CentralWorld" />
        <Label value="Cetaphil" />
        <Label value="Ch7HD" />
        <Label value="Chang" />
        <Label value="Channel 3 HD" />
        <Label value="Chao Phraya Express Boat" />
        <Label value="Chaophya Hospital" />
        <Label value="Chester's" />
        <Label value="Chevrolet" />
        <Label value="Chewathai" />
        <Label value="Cho Cosmetics" />
        <Label value="Chulabhorn Hospital" />
        <Label value="Chularat Hospital Group" />
        <Label value="Citi" />
        <Label value="Clean &amp; Clear" />
        <Label value="Clear" />
        <Label value="Clear Nose" />
        <Label value="Clinique" />
        <Label value="Coca-Cola" />
        <Label value="Cocoburi" />
        <Label value="Colgate" />
        <Label value="Cornetto" />
        <Label value="Corsair" />
        <Label value="Crystal Drinking Water" />
        <Label value="Cubic Bread" />
        <Label value="Cute Press" />
        <Label value="D-nee" />
        <Label value="DENTISTE'" />
        <Label value="DON DON DONKI" />
        <Label value="DUTCHIE YOGHURT" />
        <Label value="Daikin" />
        <Label value="Daily News" />
        <Label value="Dairy Queen" />
        <Label value="Daradaily" />
        <Label value="Dell" />
        <Label value="Dentyne" />
        <Label value="Dhipaya Insurance" />
        <Label value="Diamond Brand" />
        <Label value="Dibuk Hospital" />
        <Label value="Digital Tips" />
        <Label value="Dna soy milk" />
        <Label value="Dohome" />
        <Label value="Doi Kham" />
        <Label value="Dolfin" />
        <Label value="Domino's Pizza" />
        <Label value="Double A" />
        <Label value="Dove" />
        <Label value="Dr.Jill" />
        <Label value="Ducati" />
        <Label value="Dulux" />
        <Label value="Dumex" />
        <Label value="Dunkin'" />
        <Label value="Dusit Thani" />
        <Label value="Dutch Mill" />
        <Label value="Dyson" />
        <Label value="ECOVACS" />
        <Label value="ESTRO" />
        <Label value="ETUDE" />
        <Label value="Eglips" />
        <Label value="Electrolux" />
        <Label value="Elephant Gypsum Board" />
        <Label value="Emporium" />
        <Label value="Emquartier" />
        <Label value="Enfa" />
        <Label value="Entravision MediaDonuts" />
        <Label value="Epson" />
        <Label value="Esso" />
        <Label value="Estee Lauder" />
        <Label value="Eucerin" />
        <Label value="Eurofood" />
        <Label value="Expedia" />
        <Label value="FINN MOBILE" />
        <Label value="FINNOMENA" />
        <Label value="FUJIFILM" />
        <Label value="FWD" />
        <Label value="Facebook" />
        <Label value="FamilyMart" />
        <Label value="Fanta" />
        <Label value="Farm Design" />
        <Label value="Fashionisland" />
        <Label value="Ferrari" />
        <Label value="Ferrero Rocher" />
        <Label value="Five Star Chicken" />
        <Label value="Flash Express" />
        <Label value="Foodland" />
        <Label value="Ford" />
        <Label value="Foremost" />
        <Label value="Frasers Property Home" />
        <Label value="Fuji Restaurant" />
        <Label value="Future Trends" />
        <Label value="GD-Jewelry" />
        <Label value="GM Live" />
        <Label value="GMM25" />
        <Label value="GPX" />
        <Label value="GRAND UNITY" />
        <Label value="Garena" />
        <Label value="Garnier" />
        <Label value="Gateway Ekamai" />
        <Label value="Gaysorn Village" />
        <Label value="Generali" />
        <Label value="Giffarine" />
        <Label value="Glico" />
        <Label value="Global House" />
        <Label value="Gourmet Market" />
        <Label value="Government Housing Bank" />
        <Label value="Government Saving Bank" />
        <Label value="Grab" />
        <Label value="HERSHEY'S" />
        <Label value="HIS" />
        <Label value="HOT POT BUFFET" />
        <Label value="HP" />
        <Label value="Hada Labo" />
        <Label value="Haier" />
        <Label value="Harley-Davidson" />
        <Label value="Häagen-Dazs" />
        <Label value="Häfele" />
        <Label value="Head and Shoulders" />
        <Label value="Heineken" />
        <Label value="Heinz" />
        <Label value="Herbal Essences" />
        <Label value="Hi-Q" />
        <Label value="Hilton" />
        <Label value="Hino" />
        <Label value="Hitachi" />
        <Label value="Holika Holika" />
        <Label value="HomePro" />
        <Label value="Honda" />
        <Label value="Hua Seng Heng" />
        <Label value="Huachiew Hospital" />
        <Label value="Huawei" />
        <Label value="Huggies" />
        <Label value="Hyatt Regency" />
        <Label value="Hyundai" />
        <Label value="ICBC Thai Commercial Bank" />
        <Label value="ICHITAN" />
        <Label value="ICONSIAM" />
        <Label value="IKEA" />
        <Label value="IN2IT" />
        <Label value="INSEE" />
        <Label value="IRPC" />
        <Label value="ISUZU" />
        <Label value="Index Living Mall" />
        <Label value="Instagram" />
        <Label value="InterContinental" />
        <Label value="Inzpy" />
        <Label value="Islamic Bank" />
        <Label value="J&amp;T Express" />
        <Label value="JD" />
        <Label value="JIB" />
        <Label value="JOHNSON'S" />
        <Label value="JORAKAY" />
        <Label value="Jaymart" />
        <Label value="Jele Beautie" />
        <Label value="Jones Salad" />
        <Label value="Jotun" />
        <Label value="Joylada" />
        <Label value="Jubilee Diamond" />
        <Label value="K-Village" />
        <Label value="KFC" />
        <Label value="KOHLER" />
        <Label value="KTC" />
        <Label value="Kaidee" />
        <Label value="Kasemrad Hospital" />
        <Label value="Kasikorn Bank" />
        <Label value="Kawasaki" />
        <Label value="Keeway" />
        <Label value="Kerry Express" />
        <Label value="Khaosod" />
        <Label value="Kia" />
        <Label value="Kiatnakin Phatra Bank" />
        <Label value="Kiehl's" />
        <Label value="Kinder" />
        <Label value="King Chulalongkorn Memorial Hospital" />
        <Label value="King Power" />
        <Label value="Kingston" />
        <Label value="KitKat" />
        <Label value="Klook" />
        <Label value="Kluaynamthai Hospital" />
        <Label value="Knorr" />
        <Label value="Kodomo" />
        <Label value="KomChadLuek" />
        <Label value="Koncept Furniture" />
        <Label value="Kouen" />
        <Label value="KratingDaeng" />
        <Label value="Krispy Kreme" />
        <Label value="Krung Siam St.Calos Medical Centre" />
        <Label value="Krungsri Bank" />
        <Label value="Krungsri First Choice" />
        <Label value="Krungthai Bank" />
        <Label value="L'OCCITANE" />
        <Label value="L'Oréal Paris" />
        <Label value="LALIN Property" />
        <Label value="LAMPTAN" />
        <Label value="LANEIGE" />
        <Label value="LEO" />
        <Label value="LG" />
        <Label value="LINE BK" />
        <Label value="LINE MAN" />
        <Label value="LINE WEBTOON" />
        <Label value="LPN" />
        <Label value="LUX" />
        <Label value="La Mer" />
        <Label value="La Roche-Posay" />
        <Label value="Lactasoy" />
        <Label value="Ladies of Digital Age" />
        <Label value="Lalamove" />
        <Label value="Lamoon" />
        <Label value="Lancôme" />
        <Label value="Land Rover" />
        <Label value="Land and Houses" />
        <Label value="Land and Houses Bank" />
        <Label value="Laurier My Brand" />
        <Label value="Lawson108" />
        <Label value="Lays" />
        <Label value="Lazada" />
        <Label value="LazMall" />
        <Label value="Le Méridien" />
        <Label value="Le Pan Bakery" />
        <Label value="Leica" />
        <Label value="Lelux Plastic Surgery Hospital" />
        <Label value="Lenovo" />
        <Label value="Lesasha" />
        <Label value="Lexus" />
        <Label value="Lienjang" />
        <Label value="Lion Air" />
        <Label value="LnwShop" />
        <Label value="Logitech" />
        <Label value="Lotus's" />
        <Label value="M-150" />
        <Label value="MAGGI" />
        <Label value="MANSOME" />
        <Label value="MBK Center" />
        <Label value="MCOT" />
        <Label value="MEILINDA" />
        <Label value="MERREZ'CA" />
        <Label value="MG" />
        <Label value="MIKIMOTO" />
        <Label value="MILO" />
        <Label value="MINI" />
        <Label value="MK Restaurants" />
        <Label value="MOGEN" />
        <Label value="MRT" />
        <Label value="MSI" />
        <Label value="MSIG" />
        <Label value="MTI" />
        <Label value="Magnolia Quality Development Corporation" />
        <Label value="Magnum" />
        <Label value="Mahachai Hospital" />
        <Label value="Major Cineplex" />
        <Label value="Major Development" />
        <Label value="Makro" />
        <Label value="Malee" />
        <Label value="Mama" />
        <Label value="Mamonde" />
        <Label value="MamyPoko" />
        <Label value="Manager Online" />
        <Label value="Marketeer" />
        <Label value="Marketing Oops" />
        <Label value="Marriott" />
        <Label value="Maserati" />
        <Label value="MaxValu" />
        <Label value="Maybelline New York" />
        <Label value="Mazda" />
        <Label value="McDonald's" />
        <Label value="McLaren" />
        <Label value="Mee Cosmetics" />
        <Label value="Megabangna" />
        <Label value="Meiji" />
        <Label value="Mellow for Kids" />
        <Label value="Mentos" />
        <Label value="Mercedes-Benz" />
        <Label value="Mercure" />
        <Label value="Merries" />
        <Label value="Meta" />
        <Label value="Michelin" />
        <Label value="Mille" />
        <Label value="Minéré" />
        <Label value="Miniso" />
        <Label value="Ministry of Public Health" />
        <Label value="Minute Maid" />
        <Label value="Mission Hospital" />
        <Label value="Mister Donut" />
        <Label value="Mister Robot" />
        <Label value="Mistine" />
        <Label value="Mitr Phol Sugar" />
        <Label value="Mitsubishi" />
        <Label value="Miyabi Grill" />
        <Label value="MizuMi" />
        <Label value="Moccona" />
        <Label value="Mommy Bear" />
        <Label value="Mono 29" />
        <Label value="Motorola" />
        <Label value="Mövenpick" />
        <Label value="Muang Thai Life" />
        <Label value="Munkong Property" />
        <Label value="M•A•C Cosmetics" />
        <Label value="NESCAFÉ" />
        <Label value="NESVITA" />
        <Label value="NIVEA" />
        <Label value="NT Broadband" />
        <Label value="NT Cloud" />
        <Label value="NYX" />
        <Label value="Nakhonchaiair" />
        <Label value="Nakornthon Hospital" />
        <Label value="Nami" />
        <Label value="Namthip" />
        <Label value="Narai Property" />
        <Label value="NationTV" />
        <Label value="National Broadcasting Services of Thailand" />
        <Label value="National Telecom" />
        <Label value="Naturegift" />
        <Label value="Nestlé Pure Life" />
        <Label value="Neutrogena" />
        <Label value="Newtv" />
        <Label value="Ngerntidlor" />
        <Label value="Nikon" />
        <Label value="Nippon Paint" />
        <Label value="Nissan" />
        <Label value="Nitipon Clinic" />
        <Label value="Noble Development" />
        <Label value="Nok Air" />
        <Label value="Nonthavej Hospital" />
        <Label value="Novotel" />
        <Label value="OPPO" />
        <Label value="OREO" />
        <Label value="Oab's Soap" />
        <Label value="Oakwood" />
        <Label value="Ocean Life Insurance" />
        <Label value="Oishi Drink" />
        <Label value="Oishi Food" />
        <Label value="Olay" />
        <Label value="Onegems" />
        <Label value="Ootoya Japanese Restaurant" />
        <Label value="Oriental Princess" />
        <Label value="Origin Property" />
        <Label value="Origins" />
        <Label value="Ovaltine" />
        <Label value="PABLO" />
        <Label value="PAÑPURI" />
        <Label value="PMG Hospital" />
        <Label value="POND'S" />
        <Label value="PPTV" />
        <Label value="PTG Energy" />
        <Label value="PTT" />
        <Label value="PTT NGV" />
        <Label value="Panasonic" />
        <Label value="Pandora" />
        <Label value="Pantene" />
        <Label value="Pantip" />
        <Label value="Paolo Hospital" />
        <Label value="Paula's Choice" />
        <Label value="Peachy" />
        <Label value="Penguin Eat Shabu" />
        <Label value="Pepsi" />
        <Label value="Peptein" />
        <Label value="Petch Mangkorn Jewelry" />
        <Label value="Petchchompoo Jewelry" />
        <Label value="Peugeot" />
        <Label value="Philips" />
        <Label value="Phyathai Hospital" />
        <Label value="Physicians Formula" />
        <Label value="Pigeon" />
        <Label value="Pioneer" />
        <Label value="Piyavate Hospital" />
        <Label value="Pizza Hut" />
        <Label value="Pocky" />
        <Label value="Police General Hospital" />
        <Label value="Pornkasem Clinic" />
        <Label value="Porsche" />
        <Label value="Positioning Magazine" />
        <Label value="PostToday" />
        <Label value="Power Buy" />
        <Label value="Prachatai" />
        <Label value="Praram 9 hospital" />
        <Label value="Prima" />
        <Label value="Pringles" />
        <Label value="Prinsiri" />
        <Label value="Property Perfect" />
        <Label value="Protex" />
        <Label value="Proud Gems" />
        <Label value="Prudential" />
        <Label value="Pruksa" />
        <Label value="Pullman" />
        <Label value="Pumpnom" />
        <Label value="Puriku" />
        <Label value="Q.House" />
        <Label value="RAD Cosmetics" />
        <Label value="RAN_cosmetic" />
        <Label value="RAiNMaker" />
        <Label value="Rabbit LINE Pay" />
        <Label value="Rajavithi Hospital" />
        <Label value="Ramkhamhaeng Hospital" />
        <Label value="Rascal + Friends" />
        <Label value="Ready Energy Drink" />
        <Label value="Rejoice" />
        <Label value="Renaissance" />
        <Label value="Revlon" />
        <Label value="Richell Baby" />
        <Label value="Robinson" />
        <Label value="Rojukiss" />
        <Label value="Rolls-Royce" />
        <Label value="Rosdee" />
        <Label value="Ruam Chai Pracharug Hospital" />
        <Label value="S&amp;P" />
        <Label value="S-26" />
        <Label value="SANWA" />
        <Label value="SB Design Square" />
        <Label value="SC ASSET" />
        <Label value="SENA Development" />
        <Label value="SF Cinema" />
        <Label value="SHERA" />
        <Label value="SHOW DC" />
        <Label value="SIAMWELL JEWELRY" />
        <Label value="SINGHA COMPLEX" />
        <Label value="SK-II" />
        <Label value="SNAILWHITE" />
        <Label value="SPY Wine Cooler" />
        <Label value="STIEBEL ELTRON" />
        <Label value="SUSCO" />
        <Label value="Saint Louis Hospital" />
        <Label value="Salika" />
        <Label value="Samitivej Hospital" />
        <Label value="Samsung" />
        <Label value="Samyan Mitrtown" />
        <Label value="SangSom" />
        <Label value="Sansiri" />
        <Label value="Santa Fe' Steak" />
        <Label value="Schneider Electric" />
        <Label value="Scotch" />
        <Label value="Seacon Square" />
        <Label value="Senka" />
        <Label value="Sensodyne" />
        <Label value="Shangri-La Hotel" />
        <Label value="Shell" />
        <Label value="Sheraton" />
        <Label value="Shizuoka" />
        <Label value="Shopee" />
        <Label value="ShopeePay" />
        <Label value="Siam Cement Group" />
        <Label value="Siam Center" />
        <Label value="Siam Commercial Bank" />
        <Label value="Siam Discovery" />
        <Label value="Siam Kubota" />
        <Label value="Siam Paragon" />
        <Label value="Siam Square One" />
        <Label value="Siam Takashimaya" />
        <Label value="Sikarin Hospital" />
        <Label value="Singha Beer" />
        <Label value="Singha Drinking Water" />
        <Label value="Singha Estate" />
        <Label value="Siriraj Piyamaharajkarun Hospital" />
        <Label value="Sizzler" />
        <Label value="Smooth-E" />
        <Label value="Smooto Japan" />
        <Label value="Soda Singha" />
        <Label value="Sofitel Hotel" />
        <Label value="Sombat Tour" />
        <Label value="Sony" />
        <Label value="Sponsor" />
        <Label value="Spring News" />
        <Label value="Sprinkle" />
        <Label value="Sri panwa" />
        <Label value="Srichand" />
        <Label value="Srisawad" />
        <Label value="Starbucks" />
        <Label value="Studio 7" />
        <Label value="Sukumvit Hospital" />
        <Label value="Sulwhasoo" />
        <Label value="SunSnackDunk" />
        <Label value="Sunbites" />
        <Label value="Sunrise Tacos" />
        <Label value="Sunsilk" />
        <Label value="Supalai" />
        <Label value="Supermom" />
        <Label value="Sushi Hiro" />
        <Label value="Suzuki" />
        <Label value="Swensen's" />
        <Label value="Swissôtel Hotel" />
        <Label value="Syn Mun Kong Insurance" />
        <Label value="Synphaet Children Hospital" />
        <Label value="Synphaet Hospital" />
        <Label value="TCL" />
        <Label value="TER Cosmetics" />
        <Label value="THAI Smile Airways" />
        <Label value="THE STANDARD" />
        <Label value="THEFACESHOP" />
        <Label value="THREE" />
        <Label value="TISCO" />
        <Label value="TMBThanachart Bank" />
        <Label value="TNN" />
        <Label value="TOA" />
        <Label value="TOTO" />
        <Label value="TPI Polene" />
        <Label value="TRESemmé" />
        <Label value="TV Direct" />
        <Label value="TV5" />
        <Label value="Taokaenoi" />
        <Label value="TechMatrix" />
        <Label value="Techsauce" />
        <Label value="Tefal" />
        <Label value="Tenjo" />
        <Label value="Terminal21" />
        <Label value="Texas Chicken" />
        <Label value="Thai Airways" />
        <Label value="Thai Credit Retail Bank" />
        <Label value="Thai Life Insurance" />
        <Label value="Thai PBS" />
        <Label value="Thai Post" />
        <Label value="Thai Watsadu" />
        <Label value="Thai-Denmark" />
        <Label value="Thailand Post" />
        <Label value="Thainakarin Hospital" />
        <Label value="ThairathTV" />
        <Label value="Thairung" />
        <Label value="Thammasat University Hospital" />
        <Label value="Thanachart Insurance" />
        <Label value="The History Of Whoo" />
        <Label value="The MATTER" />
        <Label value="The Mall" />
        <Label value="The Nation" />
        <Label value="The Opener" />
        <Label value="The People" />
        <Label value="The Pizza Company" />
        <Label value="The Story" />
        <Label value="The Street" />
        <Label value="The Transport" />
        <Label value="Thonburi Hospital" />
        <Label value="Thongbai Burapha Jewelry" />
        <Label value="Thumbsup" />
        <Label value="Tiger Brand" />
        <Label value="TikTok" />
        <Label value="Tipco" />
        <Label value="Tops" />
        <Label value="Toshiba" />
        <Label value="Toyota" />
        <Label value="Traveloka" />
        <Label value="Triumph" />
        <Label value="True Music" />
        <Label value="True Sports" />
        <Label value="True4U" />
        <Label value="TrueID" />
        <Label value="TrueMoney" />
        <Label value="TrueMove H" />
        <Label value="TrueOnline" />
        <Label value="TrueShopping" />
        <Label value="TrueVisions" />
        <Label value="Twelve Plus" />
        <Label value="Twitter" />
        <Label value="USTAR Cosmetics" />
        <Label value="UZIcosmetic" />
        <Label value="Umay+" />
        <Label value="Unif" />
        <Label value="United Overseas Bank" />
        <Label value="Unlockmen" />
        <Label value="Vajira Hospital" />
        <Label value="Vaseline" />
        <Label value="Vejthani Hospital" />
        <Label value="Verasu" />
        <Label value="Vespa" />
        <Label value="Vibharam Hospital" />
        <Label value="Vibhavadi Hospital" />
        <Label value="Vichaiyut Hospital" />
        <Label value="Vichy" />
        <Label value="Vietjet" />
        <Label value="ViewSonic" />
        <Label value="Vijittra's Jewellery" />
        <Label value="Villa Market" />
        <Label value="Viriyah Insurance" />
        <Label value="Vitamilk" />
        <Label value="Voice TV" />
        <Label value="Volvo" />
        <Label value="WISESIGHT" />
        <Label value="Wall's" />
        <Label value="Weber" />
        <Label value="Western Digital" />
        <Label value="Wet n Wild" />
        <Label value="Workpoint" />
        <Label value="Wuttisak" />
        <Label value="Xiaomi" />
        <Label value="Yamaha" />
        <Label value="Yanhee Hospital" />
        <Label value="Yaowarat Krungthep Jewelry" />
        <Label value="Yayoi Japanese Restaurant" />
        <Label value="YenYen" />
        <Label value="YouTube" />
        <Label value="Yves Rocher" />
        <Label value="ZEN Japanese Restaurant" />
        <Label value="Zeer Rangsit" />
        <Label value="a day" />
        <Label value="airasia" />
        <Label value="beartai" />
        <Label value="dtac" />
        <Label value="est" />
        <Label value="foodpanda" />
        <Label value="iStudio" />
        <Label value="ibis" />
        <Label value="innisfree" />
        <Label value="mMilk" />
        <Label value="modernform furniture" />
        <Label value="my by NT" />
        <Label value="one31" />
        <Label value="settrade" />
        <Label value="vivo" />
        <Label value="สมหวัง เงินสั่งได้" />
        <Label value="อาคเนย์" />
        <Label value="เรื่องเล่าเช้านี้" />
        <Label value="Viu" />
        <Label value="Netflix" />
        <Label value="Disney+" />
        <Label value="WeTV" />
        <Label value="Prime Video" />
        <Label value="iQIYI" />
        <Label value="AIS PLAY" />
        <Label value="HBO" />
        <Label value="SUQQU" />
        <Label value="Asahi" />
        <Label value="CeraVe" />
        <Label value="CHANEL" />
        <Label value="GUCCI" />
        <Label value="KANEBO" />
        <Label value="KATE TOKYO" />
        <Label value="Nike" />
        <Label value="PUMA" />
        <Label value="Reebok" />
        <Label value="Yves Saint Laurent" />
        <Label value="พรรคก้าวไกล" />
        <Label value="พรรคชาติไทยพัฒนา" />
        <Label value="พรรคไทยภักดี" />
        <Label value="พรรคไทยสร้างไทย" />
        <Label value="พรรคประชาธิปัตย์" />
        <Label value="พรรคเพื่อไทย" />
        <Label value="พรรคพลังประชารัฐ" />
        <Label value="พรรคภูมิใจไทย" />
        <Label value="พรรครวมไทยสร้างชาติ" />
        <Label value="พรรคเสรีรวมไทย" />
        <Label value="สำนักงานปลัดกระทรวงกลาโหม" />
        <Label value="LOOX TV" />
        <Label value="AURA Mineral Water" />
        <Label value="Purra" />
        <Label value="SIAM PIWAT" />
        <Label value="SIAM PREMIUM OUTLETS BANGKOK" />
        <Label value="พรรคชาติพัฒนากล้า" />
        <Label value="Corona" />
        <Label value="MY BEER" />
        <Label value="Snowy Weizen" />
        <Label value="Carlsberg" />
        <Label value="Kronenbourg" />
        <Label value="Hoegaarden" />
        <Label value="Budweiser" />
        <Label value="Mont Fleur" />
        <Label value="Haru Cold Brew Green Tea" />
        <Label value="Kadprai" />
        <Label value="Boss Coffee" />
        <Label value="Bomi" />
        <Label value="Metropolitan Electricity Authority" />
        <Label value="Arabus Coffee" />
        <Label value="สำนักงานตำรวจแห่งชาติ" />
        <Label value="สำนักงานเทคโนโลยีสารสนเทศและการสื่อสาร - สำนักงานตำรวจแห่งชาติ" />
        <Label value="Export-Import Bank" />
        <Label value="BRITANIA" />
        <Label value="BANK OF THAILAND" />
        <Label value="Token X" />
        <Label value="SCBX" />
        <Label value="SCB Abacus" />
        <Label value="SCB 10X" />
        <Label value="MONIX" />
        <Label value="InnovestX" />
        <Label value="CardX" />
        <Label value="AutoX" />
        <Label value="Alpha X" />
        <Label value="era-won" />
        <Label value="absorba" />
        <Label value="Chulalongkorn University" />
        <Label value="Bangkok University" />
        <Label value="besico" />
        <Label value="Robinhood" />
        <Label value="Thammasat University" />
        <Label value="era-won beauty" />
        <Label value="Krungthai AXA" />
        <Label value="CPRAM" />
        <Label value="Charoen Pokphand Group C.P. Group" />
        <Label value="CPALL" />
        <Label value="Schweppes" />
        <Label value="SINGHA LEMON SODA" />
        <Label value="DHL" />
        <Label value="Ninja Van" />
        <Label value="SPX Express" />
        <Label value="Tesla" />
        <Label value="การท่องเที่ยวแห่งประเทศไทย" />
        <Label value="Bangkok Hospital Siriroj" />
        <Label value="Bangkok Insurance" />
        <Label value="Bangkoklife" />
        <Label value="Bangmod Hospital" />
        <Label value="Bangpakok Hospital" />
        <Label value="Bangpo General Hospital" />
        <Label value="Banyan Tree" />
        <Label value="Bar B Q Plaza" />
        <Label value="Baskin-Robbins" />
        <Label value="BeNice" />
        <Label value="Bear Brand" />
        <Label value="Beauty Buffet Shop" />
        <Label value="Beger Paint" />
        <Label value="Beko" />
        <Label value="BenQ" />
        <Label value="Benefit Cosmetics" />
        <Label value="Bhumirajnakarin Kidney Institute Hospital" />
        <Label value="Big C" />
        <Label value="Biotherm Homme" />
        <Label value="Birdy" />
        <Label value="Bisous Bisous" />
        <Label value="Bitkub" />
        <Label value="Bluebik" />
        <Label value="Blúport Huahin" />
        <Label value="BnB home" />
        <Label value="Bobbi Brown" />
        <Label value="Boonthavorn" />
        <Label value="Brand Buffet" />
        <Label value="BrandAge" />
        <Label value="Bridgestone" />
        <Label value="Browit By Nongchat" />
        <Label value="Bua Concrete" />
        <Label value="Bumrungrad International Hospital" />
        <Label value="Burger King" />
        <Label value="C-vitt" />
        <Label value="CALTEX" />
        <Label value="CH8" />
        <Label value="CIMB" />
        <Label value="CJ MORE" />
        <Label value="CNMI Ramathibodi Hospital" />
        <Label value="CONWOOD" />
        <Label value="COOLfahrenheit" />
        <Label value="COSLUXE" />
        <Label value="COTTO" />
        <Label value="CP" />
        <Label value="CPAC" />
        <Label value="CREATIVE TALK" />
        <Label value="Café Amazon" />
        <Label value="Camillian Hospital" />
        <Label value="Canon" />
        <Label value="Captain Coating" />
        <Label value="Carabao" />
        <Label value="Care" />
        <Label value="Carrier" />
        <Label value="Casio" />
        <Label value="Cat Radio" />
        <Label value="Cathy Doll" />
        <Label value="Centara" />
        <Label value="Central Department Store" />
        <Label value="CentralWorld" />
        <Label value="Cetaphil" />
        <Label value="Ch7HD" />
        <Label value="Chang" />
        <Label value="Channel 3 HD" />
        <Label value="Chao Phraya Express Boat" />
        <Label value="Chaophya Hospital" />
        <Label value="Chester's" />
        <Label value="Chevrolet" />
        <Label value="Chewathai" />
        <Label value="Cho Cosmetics" />
        <Label value="Chulabhorn Hospital" />
        <Label value="Chularat Hospital Group" />
        <Label value="Citi" />
        <Label value="Clean &amp; Clear" />
        <Label value="Clear" />
        <Label value="Clear Nose" />
        <Label value="Clinique" />
        <Label value="Coca-Cola" />
        <Label value="Cocoburi" />
        <Label value="Colgate" />
        <Label value="Cornetto" />
        <Label value="Corsair" />
        <Label value="Crystal Drinking Water" />
        <Label value="Cubic Bread" />
        <Label value="Cute Press" />
        <Label value="D-nee" />
        <Label value="DENTISTE'" />
        <Label value="DON DON DONKI" />
        <Label value="DUTCHIE YOGHURT" />
        <Label value="Daikin" />
        <Label value="Daily News" />
        <Label value="Dairy Queen" />
        <Label value="Daradaily" />
        <Label value="Dell" />
        <Label value="Dentyne" />
        <Label value="Dhipaya Insurance" />
        <Label value="Diamond Brand" />
        <Label value="Dibuk Hospital" />
        <Label value="Digital Tips" />
        <Label value="Dna soy milk" />
        <Label value="Dohome" />
        <Label value="Doi Kham" />
        <Label value="Dolfin" />
        <Label value="Domino's Pizza" />
        <Label value="Double A" />
        <Label value="Dove" />
        <Label value="Dr.Jill" />
        <Label value="Ducati" />
        <Label value="Dulux" />
        <Label value="Dumex" />
        <Label value="Dunkin'" />
        <Label value="Dusit Thani" />
        <Label value="Dutch Mill" />
        <Label value="Dyson" />
        <Label value="ECOVACS" />
        <Label value="ESTRO" />
        <Label value="ETUDE" />
        <Label value="Eglips" />
        <Label value="Electrolux" />
        <Label value="Elephant Gypsum Board" />
        <Label value="Emporium" />
        <Label value="Emquartier" />
        <Label value="Enfa" />
        <Label value="Entravision MediaDonuts" />
        <Label value="Epson" />
        <Label value="Esso" />
        <Label value="Estee Lauder" />
        <Label value="Eucerin" />
        <Label value="Eurofood" />
        <Label value="Expedia" />
        <Label value="FINN MOBILE" />
        <Label value="FINNOMENA" />
        <Label value="FUJIFILM" />
        <Label value="FWD" />
        <Label value="Facebook" />
        <Label value="FamilyMart" />
        <Label value="Fanta" />
        <Label value="Farm Design" />
        <Label value="Fashionisland" />
        <Label value="Ferrari" />
        <Label value="Ferrero Rocher" />
        <Label value="Five Star Chicken" />
        <Label value="Flash Express" />
        <Label value="Foodland" />
        <Label value="Ford" />
        <Label value="Foremost" />
        <Label value="Frasers Property Home" />
        <Label value="Fuji Restaurant" />
        <Label value="Future Trends" />
        <Label value="GD-Jewelry" />
        <Label value="GM Live" />
        <Label value="GMM25" />
        <Label value="GPX" />
        <Label value="GRAND UNITY" />
        <Label value="Garena" />
        <Label value="Garnier" />
        <Label value="Gateway Ekamai" />
        <Label value="Gaysorn Village" />
        <Label value="Generali" />
        <Label value="Giffarine" />
        <Label value="Glico" />
        <Label value="Global House" />
        <Label value="Gourmet Market" />
        <Label value="Government Housing Bank" />
        <Label value="Government Saving Bank" />
        <Label value="Grab" />
        <Label value="HERSHEY'S" />
        <Label value="HIS" />
        <Label value="HOT POT BUFFET" />
        <Label value="HP" />
        <Label value="Hada Labo" />
        <Label value="Haier" />
        <Label value="Harley-Davidson" />
        <Label value="Häagen-Dazs" />
        <Label value="Häfele" />
        <Label value="Head and Shoulders" />
        <Label value="Heineken" />
        <Label value="Heinz" />
        <Label value="Herbal Essences" />
        <Label value="Hi-Q" />
        <Label value="Hilton" />
        <Label value="Hino" />
        <Label value="Hitachi" />
        <Label value="Holika Holika" />
        <Label value="HomePro" />
        <Label value="Honda" />
        <Label value="Hua Seng Heng" />
        <Label value="Huachiew Hospital" />
        <Label value="Huawei" />
        <Label value="Huggies" />
        <Label value="Hyatt Regency" />
        <Label value="Hyundai" />
        <Label value="ICBC Thai Commercial Bank" />
        <Label value="ICHITAN" />
        <Label value="ICONSIAM" />
        <Label value="IKEA" />
        <Label value="IN2IT" />
        <Label value="INSEE" />
        <Label value="IRPC" />
        <Label value="ISUZU" />
        <Label value="Index Living Mall" />
        <Label value="Instagram" />
        <Label value="InterContinental" />
        <Label value="Inzpy" />
        <Label value="Islamic Bank" />
        <Label value="J&amp;T Express" />
        <Label value="JD" />
        <Label value="JIB" />
        <Label value="JOHNSON'S" />
        <Label value="JORAKAY" />
        <Label value="Jaymart" />
        <Label value="Jele Beautie" />
        <Label value="Jones Salad" />
        <Label value="Jotun" />
        <Label value="Joylada" />
        <Label value="Jubilee Diamond" />
        <Label value="K-Village" />
        <Label value="KFC" />
        <Label value="KOHLER" />
        <Label value="KTC" />
        <Label value="Kaidee" />
        <Label value="Kasemrad Hospital" />
        <Label value="Kasikorn Bank" />
        <Label value="Kawasaki" />
        <Label value="Keeway" />
        <Label value="Kerry Express" />
        <Label value="Khaosod" />
        <Label value="Kia" />
        <Label value="Kiatnakin Phatra Bank" />
        <Label value="Kiehl's" />
        <Label value="Kinder" />
        <Label value="King Chulalongkorn Memorial Hospital" />
        <Label value="King Power" />
        <Label value="Kingston" />
        <Label value="KitKat" />
        <Label value="Klook" />
        <Label value="Kluaynamthai Hospital" />
        <Label value="Knorr" />
        <Label value="Kodomo" />
        <Label value="KomChadLuek" />
        <Label value="Koncept Furniture" />
        <Label value="Kouen" />
        <Label value="KratingDaeng" />
        <Label value="Krispy Kreme" />
        <Label value="Krung Siam St.Calos Medical Centre" />
        <Label value="Krungsri Bank" />
        <Label value="Krungsri First Choice" />
        <Label value="Krungthai Bank" />
        <Label value="L'OCCITANE" />
        <Label value="L'Oréal Paris" />
        <Label value="LALIN Property" />
        <Label value="LAMPTAN" />
        <Label value="LANEIGE" />
        <Label value="LEO" />
        <Label value="LG" />
        <Label value="LINE BK" />
        <Label value="LINE MAN" />
        <Label value="LINE WEBTOON" />
        <Label value="LPN" />
        <Label value="LUX" />
        <Label value="La Mer" />
        <Label value="La Roche-Posay" />
        <Label value="Lactasoy" />
        <Label value="Ladies of Digital Age" />
        <Label value="Lalamove" />
        <Label value="Lamoon" />
        <Label value="Lancôme" />
        <Label value="Land Rover" />
        <Label value="Land and Houses" />
        <Label value="Land and Houses Bank" />
        <Label value="Laurier My Brand" />
        <Label value="Lawson108" />
        <Label value="Lays" />
        <Label value="Lazada" />
        <Label value="LazMall" />
        <Label value="Le Méridien" />
        <Label value="Le Pan Bakery" />
        <Label value="Leica" />
        <Label value="Lelux Plastic Surgery Hospital" />
        <Label value="Lenovo" />
        <Label value="Lesasha" />
        <Label value="Lexus" />
        <Label value="Lienjang" />
        <Label value="Lion Air" />
        <Label value="LnwShop" />
        <Label value="Logitech" />
        <Label value="Lotus's" />
        <Label value="M-150" />
        <Label value="MAGGI" />
        <Label value="MANSOME" />
        <Label value="MBK Center" />
        <Label value="MCOT" />
        <Label value="MEILINDA" />
        <Label value="MERREZ'CA" />
        <Label value="MG" />
        <Label value="MIKIMOTO" />
        <Label value="MILO" />
        <Label value="MINI" />
        <Label value="MK Restaurants" />
        <Label value="MOGEN" />
        <Label value="MRT" />
        <Label value="MSI" />
        <Label value="MSIG" />
        <Label value="MTI" />
        <Label value="Magnolia Quality Development Corporation" />
        <Label value="Magnum" />
        <Label value="Mahachai Hospital" />
        <Label value="Major Cineplex" />
        <Label value="Major Development" />
        <Label value="Makro" />
        <Label value="Malee" />
        <Label value="Mama" />
        <Label value="Mamonde" />
        <Label value="MamyPoko" />
        <Label value="Manager Online" />
        <Label value="Marketeer" />
        <Label value="Marketing Oops" />
        <Label value="Marriott" />
        <Label value="Maserati" />
        <Label value="MaxValu" />
        <Label value="Maybelline New York" />
        <Label value="Mazda" />
        <Label value="McDonald's" />
        <Label value="McLaren" />
        <Label value="Mee Cosmetics" />
        <Label value="Megabangna" />
        <Label value="Meiji" />
        <Label value="Mellow for Kids" />
        <Label value="Mentos" />
        <Label value="Mercedes-Benz" />
        <Label value="Mercure" />
        <Label value="Merries" />
        <Label value="Meta" />
        <Label value="Michelin" />
        <Label value="Mille" />
        <Label value="Minéré" />
        <Label value="Miniso" />
        <Label value="Ministry of Public Health" />
        <Label value="Minute Maid" />
        <Label value="Mission Hospital" />
        <Label value="Mister Donut" />
        <Label value="Mister Robot" />
        <Label value="Mistine" />
        <Label value="Mitr Phol Sugar" />
        <Label value="Mitsubishi" />
        <Label value="Miyabi Grill" />
        <Label value="MizuMi" />
        <Label value="Moccona" />
        <Label value="Mommy Bear" />
        <Label value="Mono 29" />
        <Label value="Motorola" />
        <Label value="Mövenpick" />
        <Label value="Muang Thai Life" />
        <Label value="Munkong Property" />
        <Label value="M•A•C Cosmetics" />
        <Label value="NESCAFÉ" />
        <Label value="NESVITA" />
        <Label value="NIVEA" />
        <Label value="NT Broadband" />
        <Label value="NT Cloud" />
        <Label value="NYX" />
        <Label value="Nakhonchaiair" />
        <Label value="Nakornthon Hospital" />
        <Label value="Nami" />
        <Label value="Namthip" />
        <Label value="Narai Property" />
        <Label value="NationTV" />
        <Label value="National Broadcasting Services of Thailand" />
        <Label value="National Telecom" />
        <Label value="Naturegift" />
        <Label value="Nestlé Pure Life" />
        <Label value="Neutrogena" />
        <Label value="Newtv" />
        <Label value="Ngerntidlor" />
        <Label value="Nikon" />
        <Label value="Nippon Paint" />
        <Label value="Nissan" />
        <Label value="Nitipon Clinic" />
        <Label value="Noble Development" />
        <Label value="Nok Air" />
        <Label value="Nonthavej Hospital" />
        <Label value="Novotel" />
        <Label value="OPPO" />
        <Label value="OREO" />
        <Label value="Oab's Soap" />
        <Label value="Oakwood" />
        <Label value="Ocean Life Insurance" />
        <Label value="Oishi Drink" />
        <Label value="Oishi Food" />
        <Label value="Olay" />
        <Label value="Onegems" />
        <Label value="Ootoya Japanese Restaurant" />
        <Label value="Oriental Princess" />
        <Label value="Origin Property" />
        <Label value="Origins" />
        <Label value="Ovaltine" />
        <Label value="PABLO" />
        <Label value="PAÑPURI" />
        <Label value="PMG Hospital" />
        <Label value="POND'S" />
        <Label value="PPTV" />
        <Label value="PTG Energy" />
        <Label value="PTT" />
        <Label value="PTT NGV" />
        <Label value="Panasonic" />
        <Label value="Pandora" />
        <Label value="Pantene" />
        <Label value="Pantip" />
        <Label value="Paolo Hospital" />
        <Label value="Paula's Choice" />
        <Label value="Peachy" />
        <Label value="Penguin Eat Shabu" />
        <Label value="Pepsi" />
        <Label value="Peptein" />
        <Label value="Petch Mangkorn Jewelry" />
        <Label value="Petchchompoo Jewelry" />
        <Label value="Peugeot" />
        <Label value="Philips" />
        <Label value="Phyathai Hospital" />
        <Label value="Physicians Formula" />
        <Label value="Pigeon" />
        <Label value="Pioneer" />
        <Label value="Piyavate Hospital" />
        <Label value="Pizza Hut" />
        <Label value="Pocky" />
        <Label value="Police General Hospital" />
        <Label value="Pornkasem Clinic" />
        <Label value="Porsche" />
        <Label value="Positioning Magazine" />
        <Label value="PostToday" />
        <Label value="Power Buy" />
        <Label value="Prachatai" />
        <Label value="Praram 9 hospital" />
        <Label value="Prima" />
        <Label value="Pringles" />
        <Label value="Prinsiri" />
        <Label value="Property Perfect" />
        <Label value="Protex" />
        <Label value="Proud Gems" />
        <Label value="Prudential" />
        <Label value="Pruksa" />
        <Label value="Pullman" />
        <Label value="Pumpnom" />
        <Label value="Puriku" />
        <Label value="Q.House" />
        <Label value="RAD Cosmetics" />
        <Label value="RAN_cosmetic" />
        <Label value="RAiNMaker" />
        <Label value="Rabbit LINE Pay" />
        <Label value="Rajavithi Hospital" />
        <Label value="Ramkhamhaeng Hospital" />
        <Label value="Rascal + Friends" />
        <Label value="Ready Energy Drink" />
        <Label value="Rejoice" />
        <Label value="Renaissance" />
        <Label value="Revlon" />
        <Label value="Richell Baby" />
        <Label value="Robinson" />
        <Label value="Rojukiss" />
        <Label value="Rolls-Royce" />
        <Label value="Rosdee" />
        <Label value="Ruam Chai Pracharug Hospital" />
        <Label value="S&amp;P" />
        <Label value="S-26" />
        <Label value="SANWA" />
        <Label value="SB Design Square" />
        <Label value="SC ASSET" />
        <Label value="SENA Development" />
        <Label value="SF Cinema" />
        <Label value="SHERA" />
        <Label value="SHOW DC" />
        <Label value="SIAMWELL JEWELRY" />
        <Label value="SINGHA COMPLEX" />
        <Label value="SK-II" />
        <Label value="SNAILWHITE" />
        <Label value="SPY Wine Cooler" />
        <Label value="STIEBEL ELTRON" />
        <Label value="SUSCO" />
        <Label value="Saint Louis Hospital" />
        <Label value="Salika" />
        <Label value="Samitivej Hospital" />
        <Label value="Samsung" />
        <Label value="Samyan Mitrtown" />
        <Label value="SangSom" />
        <Label value="Sansiri" />
        <Label value="Santa Fe' Steak" />
        <Label value="Schneider Electric" />
        <Label value="Scotch" />
        <Label value="Seacon Square" />
        <Label value="Senka" />
        <Label value="Sensodyne" />
        <Label value="Shangri-La Hotel" />
        <Label value="Shell" />
        <Label value="Sheraton" />
        <Label value="Shizuoka" />
        <Label value="Shopee" />
        <Label value="ShopeePay" />
        <Label value="Siam Cement Group" />
        <Label value="Siam Center" />
        <Label value="Siam Commercial Bank" />
        <Label value="Siam Discovery" />
        <Label value="Siam Kubota" />
        <Label value="Siam Paragon" />
        <Label value="Siam Square One" />
        <Label value="Siam Takashimaya" />
        <Label value="Sikarin Hospital" />
        <Label value="Singha Beer" />
        <Label value="Singha Drinking Water" />
        <Label value="Singha Estate" />
        <Label value="Siriraj Piyamaharajkarun Hospital" />
        <Label value="Sizzler" />
        <Label value="Smooth-E" />
        <Label value="Smooto Japan" />
        <Label value="Soda Singha" />
        <Label value="Sofitel Hotel" />
        <Label value="Sombat Tour" />
        <Label value="Sony" />
        <Label value="Sponsor" />
        <Label value="Spring News" />
        <Label value="Sprinkle" />
        <Label value="Sri panwa" />
        <Label value="Srichand" />
        <Label value="Srisawad" />
        <Label value="Starbucks" />
        <Label value="Studio 7" />
        <Label value="Sukumvit Hospital" />
        <Label value="Sulwhasoo" />
        <Label value="SunSnackDunk" />
        <Label value="Sunbites" />
        <Label value="Sunrise Tacos" />
        <Label value="Sunsilk" />
        <Label value="Supalai" />
        <Label value="Supermom" />
        <Label value="Sushi Hiro" />
        <Label value="Suzuki" />
        <Label value="Swensen's" />
        <Label value="Swissôtel Hotel" />
        <Label value="Syn Mun Kong Insurance" />
        <Label value="Synphaet Children Hospital" />
        <Label value="Synphaet Hospital" />
        <Label value="TCL" />
        <Label value="TER Cosmetics" />
        <Label value="THAI Smile Airways" />
        <Label value="THE STANDARD" />
        <Label value="THEFACESHOP" />
        <Label value="THREE" />
        <Label value="TISCO" />
        <Label value="TMBThanachart Bank" />
        <Label value="TNN" />
        <Label value="TOA" />
        <Label value="TOTO" />
        <Label value="TPI Polene" />
        <Label value="TRESemmé" />
        <Label value="TV Direct" />
        <Label value="TV5" />
        <Label value="Taokaenoi" />
        <Label value="TechMatrix" />
        <Label value="Techsauce" />
        <Label value="Tefal" />
        <Label value="Tenjo" />
        <Label value="Terminal21" />
        <Label value="Texas Chicken" />
        <Label value="Thai Airways" />
        <Label value="Thai Credit Retail Bank" />
        <Label value="Thai Life Insurance" />
        <Label value="Thai PBS" />
        <Label value="Thai Post" />
        <Label value="Thai Watsadu" />
        <Label value="Thai-Denmark" />
        <Label value="Thailand Post" />
        <Label value="Thainakarin Hospital" />
        <Label value="ThairathTV" />
        <Label value="Thairung" />
        <Label value="Thammasat University Hospital" />
        <Label value="Thanachart Insurance" />
        <Label value="The History Of Whoo" />
        <Label value="The MATTER" />
        <Label value="The Mall" />
        <Label value="The Nation" />
        <Label value="The Opener" />
        <Label value="The People" />
        <Label value="The Pizza Company" />
        <Label value="The Story" />
        <Label value="The Street" />
        <Label value="The Transport" />
        <Label value="Thonburi Hospital" />
        <Label value="Thongbai Burapha Jewelry" />
        <Label value="Thumbsup" />
        <Label value="Tiger Brand" />
        <Label value="TikTok" />
        <Label value="Tipco" />
        <Label value="Tops" />
        <Label value="Toshiba" />
        <Label value="Toyota" />
        <Label value="Traveloka" />
        <Label value="Triumph" />
        <Label value="True Music" />
        <Label value="True Sports" />
        <Label value="True4U" />
        <Label value="TrueID" />
        <Label value="TrueMoney" />
        <Label value="TrueMove H" />
        <Label value="TrueOnline" />
        <Label value="TrueShopping" />
        <Label value="TrueVisions" />
        <Label value="Twelve Plus" />
        <Label value="Twitter" />
        <Label value="USTAR Cosmetics" />
        <Label value="UZIcosmetic" />
        <Label value="Umay+" />
        <Label value="Unif" />
        <Label value="United Overseas Bank" />
        <Label value="Unlockmen" />
        <Label value="Vajira Hospital" />
        <Label value="Vaseline" />
        <Label value="Vejthani Hospital" />
        <Label value="Verasu" />
        <Label value="Vespa" />
        <Label value="Vibharam Hospital" />
        <Label value="Vibhavadi Hospital" />
        <Label value="Vichaiyut Hospital" />
        <Label value="Vichy" />
        <Label value="Vietjet" />
        <Label value="ViewSonic" />
        <Label value="Vijittra's Jewellery" />
        <Label value="Villa Market" />
        <Label value="Viriyah Insurance" />
        <Label value="Vitamilk" />
        <Label value="Voice TV" />
        <Label value="Volvo" />
        <Label value="WISESIGHT" />
        <Label value="Wall's" />
        <Label value="Weber" />
        <Label value="Western Digital" />
        <Label value="Wet n Wild" />
        <Label value="Workpoint" />
        <Label value="Wuttisak" />
        <Label value="Xiaomi" />
        <Label value="Yamaha" />
        <Label value="Yanhee Hospital" />
        <Label value="Yaowarat Krungthep Jewelry" />
        <Label value="Yayoi Japanese Restaurant" />
        <Label value="YenYen" />
        <Label value="YouTube" />
        <Label value="Yves Rocher" />
        <Label value="ZEN Japanese Restaurant" />
        <Label value="Zeer Rangsit" />
        <Label value="a day" />
        <Label value="airasia" />
        <Label value="beartai" />
        <Label value="dtac" />
        <Label value="est" />
        <Label value="foodpanda" />
        <Label value="iStudio" />
        <Label value="ibis" />
        <Label value="innisfree" />
        <Label value="mMilk" />
        <Label value="modernform furniture" />
        <Label value="my by NT" />
        <Label value="one31" />
        <Label value="settrade" />
        <Label value="vivo" />
        <Label value="สมหวัง เงินสั่งได้" />
        <Label value="อาคเนย์" />
        <Label value="เรื่องเล่าเช้านี้" />
        <Label value="Viu" />
        <Label value="Netflix" />
        <Label value="Disney+" />
        <Label value="WeTV" />
        <Label value="Prime Video" />
        <Label value="iQIYI" />
        <Label value="AIS PLAY" />
        <Label value="HBO" />
        <Label value="SUQQU" />
        <Label value="Asahi" />
        <Label value="CeraVe" />
        <Label value="CHANEL" />
        <Label value="GUCCI" />
        <Label value="KANEBO" />
        <Label value="KATE TOKYO" />
        <Label value="Nike" />
        <Label value="PUMA" />
        <Label value="Reebok" />
        <Label value="Yves Saint Laurent" />
        <Label value="พรรคก้าวไกล" />
        <Label value="พรรคชาติไทยพัฒนา" />
        <Label value="พรรคไทยภักดี" />
        <Label value="พรรคไทยสร้างไทย" />
        <Label value="พรรคประชาธิปัตย์" />
        <Label value="พรรคเพื่อไทย" />
        <Label value="พรรคพลังประชารัฐ" />
        <Label value="พรรคภูมิใจไทย" />
        <Label value="พรรครวมไทยสร้างชาติ" />
        <Label value="พรรคเสรีรวมไทย" />
        <Label value="สำนักงานปลัดกระทรวงกลาโหม" />
        <Label value="LOOX TV" />
        <Label value="AURA Mineral Water" />
        <Label value="Purra" />
        <Label value="SIAM PIWAT" />
        <Label value="SIAM PREMIUM OUTLETS BANGKOK" />
        <Label value="พรรคชาติพัฒนากล้า" />
        <Label value="Corona" />
        <Label value="MY BEER" />
        <Label value="Snowy Weizen" />
        <Label value="Carlsberg" />
        <Label value="Kronenbourg" />
        <Label value="Hoegaarden" />
        <Label value="Budweiser" />
        <Label value="Mont Fleur" />
        <Label value="Haru Cold Brew Green Tea" />
        <Label value="Kadprai" />
        <Label value="Boss Coffee" />
        <Label value="Bomi" />
        <Label value="Metropolitan Electricity Authority" />
        <Label value="Arabus Coffee" />
        <Label value="สำนักงานตำรวจแห่งชาติ" />
        <Label value="สำนักงานเทคโนโลยีสารสนเทศและการสื่อสาร - สำนักงานตำรวจแห่งชาติ" />
        <Label value="Export-Import Bank" />
        <Label value="BRITANIA" />
        <Label value="BANK OF THAILAND" />
        <Label value="Token X" />
        <Label value="SCBX" />
        <Label value="SCB Abacus" />
        <Label value="SCB 10X" />
        <Label value="MONIX" />
        <Label value="InnovestX" />
        <Label value="CardX" />
        <Label value="AutoX" />
        <Label value="Alpha X" />
        <Label value="era-won" />
        <Label value="absorba" />
        <Label value="Chulalongkorn University" />
        <Label value="Bangkok University" />
        <Label value="besico" />
        <Label value="Robinhood" />
        <Label value="Thammasat University" />
        <Label value="era-won beauty" />
        <Label value="Krungthai AXA" />
        <Label value="CPRAM" />
        <Label value="Charoen Pokphand Group C.P. Group" />
        <Label value="CPALL" />
        <Label value="Schweppes" />
        <Label value="SINGHA LEMON SODA" />
        <Label value="DHL" />
        <Label value="Ninja Van" />
        <Label value="SPX Express" />
        <Label value="Tesla" />
        <Label value="การท่องเที่ยวแห่งประเทศไทย" />
        </RectangleLabels>
        <Filter name="filter" toName="label" hotkey="shift+f" minlength="0" placeholder="Filter"/>
        <View whenTagName="label" whenChoiceValue="Car">
            <TextArea name="other-class" toName="image" editable="true" perRegion="true" required="false" rows="1" placeholder="Brand's name" />
        </View>
        </View>
        """,
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Process some integers.")
    parser.add_argument("--port", type=int, help="port number")
    parser.add_argument("--token", type=str, help="label studio token")

    args = parser.parse_args()
    setup(args.port, args.token)
    print("project has been set up successfully")
